image: erlang

before_script:
  - git config --global url.git@gitlab.com:shortishly.insteadOf https://github.com/shortishly

stages:
  - build

app:
  stage: build
  script:
    - make tests
  only:
    - master
